@baseUrl = http://localhost:3000

### Affiche l'ensemble des pokémons du pokedex
GET {{baseUrl}}/pokemons

### Affiche un unique pokemon
GET {{baseUrl}}/pokemon/1

### Affiche un unique pokemon
GET {{baseUrl}}/pokemon/nimportequoi

### Affiche tous les dresseurs
GET {{baseUrl}}/dresseurs

### Affiche un seul dresseur
GET {{baseUrl}}/dresseur/1

### Créer un dresseur
POST {{baseUrl}}/dresseur
content-type: application/json

{
  "nom":"Timothée"
}

### Modifie le nom d'un dresseur
PUT {{baseUrl}}/dresseur/10?name=George

### Modifie ne met pas le nom paramètre pour changer le nom d'un dresseur
PUT {{baseUrl}}/dresseur/10?test=Stephane

### Supprimer un dresseur
DELETE {{baseUrl}}/dresseur/2